### ISSUE TITLE
scan failing with unknown version of ilo

### ISSUE THREAD

**Issue by gnalawade** [allegro/ralph-cli#34]
Platform  OS X

L-SB8F26QDRV-M:scripts $ ralph-cli scan 10.65.176.11 --script="ilo.py" --dry-run --components=cpu
INFO: Running in dry-run mode, no changes will be saved in Ralph.
error running script /Users//.ralph-cli/scripts/ilo.py: exit status 1
output from script:
-->
Unknown version of iLO: %d
<--

Tested with hpilo_cli which is working fine

**Comment by xor-xor** [comment]
Hi,
Thanks for reporting this. Which version of iLO do you have on that machine?

**Comment by gnalawade** [comment]
ILO4

**Comment by xor-xor** [comment]
Thanks. Fortunately, I've found some HP machine with iLO4 installed in our DC, so I can test ralph-cli on it. I'll get back to you soon (couple of days maximum), so stay tuned.

**Comment by xor-xor** [comment]
@gnalawade - binaries for ralph-cli with support for iLO4: https://github.com/allegro/ralph-cli/releases/tag/v0.3.0

**Comment by gnalawade** [comment]
Thank you @xor-xor
