### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by gatvo** [allegro/ralph-cli#36]
I wrote my own scan script to retrieve facts from ansible so that they can be imported into ralph, but i'm having an issue that causes the scan script to error with x509: certificate signed by unknown authority.

Here is the output (note: I am using xbox as the IP for testing and it would be great to have the scan script be able to use the hostname in the same fashion):

```
# ralph-cli scan xbox --script=get_ansible_facts.py --dry-run
INFO: Running in dry-run mode, no changes will be saved in Ralph.
SSH password:
Vault password:
Get https://<domain>/api/base-objects/?ip=xbox: x509: certificate signed by unknown authority
```

**Comment by xor-xor** [comment]
Does this script work as expected when launched directly (i.e. without ralph-cli)..? If yes, could you make a gist out of it and post it here..? Thanks!

**Comment by gatvo** [comment]
Mostly, there's a lot of information that ansible doesnt seem to provide that matches the example on the ralph-cli docs and it's output can vary between different OS's. I basically just tried to map whatever I could into the format that is used in the doc and scripts provided (except that I have empty strings or null's where that info was not available). I also wanted to see how far the ralph-cli would take me without giving it all the info.... but other than that, it does run and produce JSON output like in the docs when launched directly

**Comment by xor-xor** [comment]
I've just realized that this error has nothing to do with your script - it pops up when ralph-cli tries to fetch some initial data related to your `xbox`'s IP _from your Ralph instance_ - so first of all, I'd make sure if your Ralph's server is configured properly in terms of certificates (you may check [this](https://curl.haxx.se/docs/sslcerts.html) for starters; I wouldn't rely too much on browsers here, because they usually perform a lot of crazy workarounds for misconfigured servers, so they can give you false positives).

**Comment by gatvo** [comment]
Yup, you were right, I needed to add the ca certificates using the update-ca-certificates command. After that I got this output, which is expected:

`IP address xbox doesn't have any base objects`

Now, I'm wondering if the scan script can include an option to be able to use the hostname instead of the ip address?

**Comment by xor-xor** [comment]
> Now, I'm wondering if the scan script can include an option to be able to use the hostname instead of the ip address?

At this moment, ralph-cli's scan expects a single IP address as an argument - and that IP address will be passed to your script - but what you will do with it _inside_ your script, is totally up to you (e.g. convert it to a FQDN), as long as you conform to the [Scripts Contract](http://ralph-cli.readthedocs.io/en/latest/concepts/#scripts-contract).

We have  support for FQDNs (and even IP ranges given as CIDRs) in ralph-cli's roadmap, but it's hard to tell when it will happen.
